### ISSUE TITLE
running plug-in locally

### ISSUE THREAD

**Issue by Supritha-Patil** [MarounMaroun/SO-Eclipse-Plugin#41]
I tried to locally run the code for the plugin. Exported successfully to install it. While it appears under Help>About Eclipse SDK>Installed Software, when I try a Alt+Q, the plugin does not run. Do you know what could be the issue?

**Comment by MarounMaroun** [comment]
@Supritha-Patil You should first download [PDE](https://www.eclipse.org/pde/), and then run the project as "**Eclipse Application**". This will open a new instance of Eclipse, which you should be able to run the plugin from.

**Comment by Supritha-Patil** [comment]
We did do as you mentioned. When a new instance of Eclipse opens, we try  Alt+Q and it does not work!

**Comment by MarounMaroun** [comment]
Does it work by right clicking and selecting the app from the menu?

**Comment by Supritha-Patil** [comment]
No, the 'Ask me' option does not even appear in the menu when I right click. But the surprising part is that, when run, the program has no errors and opens an instance of eclipse successfully.

**Comment by MarounMaroun** [comment]
What version of Eclipse and Java are you running?

**Comment by Supritha-Patil** [comment]
Eclipse 4.7.2 and Java 8.0

**Comment by AmitNaik07** [comment]
Hi, I got the plugin to run locally, but when I click on get answers, I get the following error:
I am not able to see any stackoverflow solutions.

`java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:448)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:980)
	at com.sohelper.ui.MyWizardDialog.nextPressed(MyWizardDialog.java:62)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:413)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.sohelper.handlers.SOHandler.execute(SOHandler.java:28)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.sohelper.ui.AnswerPage.setAnswerContent(AnswerPage.java:129)
	at com.sohelper.ui.AnswerPage.setAnswer(AnswerPage.java:157)
	at com.sohelper.ui.MyWizardDialog.lambda$0(MyWizardDialog.java:71)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	... 65 more
`

Any way to fix this?

**Comment by MarounMaroun** [comment]
@Supritha-Patil @AmitNaik07 I found the bug. Please change the line [here](https://github.com/MarounMaroun/SO-Eclipse-Plugin/blob/master/so-eclipse-plugin/src/com/sohelper/datatypes/StackoverflowAnswer.java#L38) to:

```java
Element userElement = element.select("div.post-signature").last().select("div.user-info").last().select("a").last();
```

I'll release a fix soon.

Thanks!

**Comment by MarounMaroun** [comment]
Here's a PR for the fix: https://github.com/MarounMaroun/SO-Eclipse-Plugin/pull/42/files

**Comment by MarounMaroun** [comment]
Fixed an [released](https://github.com/MarounMaroun/SO-Eclipse-Plugin/commit/b3545d6b52b860b9cd959cb81413e633f9297f5e).

**Comment by Supritha-Patil** [comment]
Works fine now. Thanks for the fix!
